# add config server details
 spring:
   cloud:
     config:
       uri: http://localhost:8012
       fail-fast: 'true'
       name: khatabook-service
       label: master
   main:
     banner-mode: "off"
   application:
     name: khatabook-service

