spring:
  main:
    banner-mode: "off"
  application:
    name: discovery-service

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    preferIpAddress: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

server:
  port: 8761

logging:
  level:
    root: info
    org:
      springframework: info
      hibernate: trace