spring:
  main:
    banner-mode: "off"
  application:
    name: notebook-service
  devtools:
    add-properties: 'true'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/notebook_db?useSSL=false

  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 200MB

server:
  port: 9600
eureka:
  instance:
    instanceId: ${spring.application.name}
    hostname: localhost
    preferIpAddress: false
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}