spring:
  main:
    banner-mode: "off"
  application:
    name: product-service
  h2:
    datasource:
      url: jdbc:h2:mem:testdb
      driverClassName: org.h2.Driver
      username: sa
      password: password
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
    console:
      enabled: 'true'
  devtools:
    add-properties: 'true'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/khatabook_db?useSSL=false

  mvc:
    throw-exception-if-no-handler-found: 'true'
  messages:
    basename: messages
  resources:
    add-mappings: 'false'
management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    sho-details: always
    group:
      custom:
        show-components: always
        show-details: always


graphql:
  servlet:
    mapping: /apis/graphql
logging:
  level:
    org:
      springframework: info
server:
  port: 6600
eureka:
  instance:
    instanceId: ${spring.application.name}
    hostname: localhost
    preferIpAddress: false
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}