spring:
  cloud:
    config:
      uri: http://localhost:8012
      fail-fast: 'true'
      name: PRODUCT-SERVICE
      label: master
  main:
    banner-mode: "off"
  application:
    name: PRODUCT-SERVICE