spring:
  main:
    banner-mode: "off"
  application:
    name: specification-service
  h2:
    datasource:
      url: jdbc:h2:mem:testdb
      driverClassName: org.h2.Driver
      username: sa
      password: password
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
    console:
      enabled: 'true'
  devtools:
    add-properties: 'true'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: https://example.org
          predicates:
            - Path=/red/{segment},/blue/{segment}
  mvc:
    throw-exception-if-no-handler-found: 'true'
  messages:
    basename: messages
  resources:
    add-mappings: 'false'
management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    sho-details: always
graphql:
  servlet:
    mapping: /apis/graphql
logging:
  level:
    root: info
    org:
      springframework: info
server:
  port: 6800
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

## Product service rout

