spring:
  cloud:
    config:
      server:
        git:
          password: mramitsingh04
          username: Amit.Singh04
          clone-on-start: 'true'
          uri: https://github.com/mramitsingh04/DairyAppConfigData.git
          skipSslValidation: true
          timeout: 10
          profileSeparator: ','
          cloneOnStart: 'true'
  application:
    name: central-config-server
server:
  port: 8012

logging:
  level:
    root: info
    org:
      springframework: info
      hibernate: trace

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: '*'