spring:
  cloud:
    config:
      uri: http://localhost:8012
      fail-fast: 'true'
      name: review-service
      label: master
    main:
       banner-mode: "off"
  application:
      name: review-service